# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      commit_secret: ${{secrets.COMMIT_SECRET}}
      USER_NAME   : tony14256
      USER_EMAIL  : tony14256@gmail.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.1'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn Install
        run: yarn
      
      - name: deploy
        run: |
          yarn deploy
          cd ./dist
          git init
          git config --global user.email ${{secrets.USER_EMAIL}}
          git config --global user.name ${{secrets.USER_NAME}}
          git status
          git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/${{secrets.USER_NAME}}/sort_animation.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy Next.js to gh-pages" 
          git push origin gh-pages -f
          echo 🤘 deploy gh-pages complete.

          
          
          
    
